title: Jianbin Gong # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Seeking a full-time software engineer position with an expected start on 06/2022. Master’s candidate with strong, analytical, managerial skills, with a wide range of industry-level project experience, including web and android application development, 5+ years of internet industry experience, strong knowledge of the business operation, and programming skills in Java, Python, C, C++, Go, Database SQL, HTML, CSS, and JavaScript.
  <br><br>
  <a href="https://www.linkedin.com/in/jianbin-gong-6a34b132/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
