title: Jianbin Gong # your name (or website title) here
logo: "/images/profile-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Seeking a full-time entry level software engineer position. Master’s candidate with strong, analytical, managerial skills, with a wide range of industry-level project experience, including web and android application development, 2-3 years of software development experience.
  <br><br>
  I also learned programming skills in Java, Python, C, Go, Database SQL, HTML, CSS, and JavaScript.
  <br><br>
  <a href="https://www.linkedin.com/in/jianbin-gong-6a34b132/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
